channels:
  - conda-forge
dependencies:
  - python=3.7*
  - pangeo-notebook=2020.08.24
  - pip=20
  - fsspec=0.7.4
  - s3fs=0.4.2
  - conda-forge/label/h5py_dev::h5py
  - h5netcdf
  - matplotlib
  - holoviews
  - geoviews-core
  - pandas
  - datashader
  - hvplot
  - panel
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/HDFGroup/zarr-python.git@hdf5
